using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using GameLauncher.Models;

namespace GameLauncher.Services;

/// <summary>
/// Loads and saves per-game controller profiles from
/// <c>Data/GameCache/{platform}/{title}/controller-profiles.json</c>.
///
/// Profiles are compatible with the Game.OS.Input companion app format
/// (SharpDX.XInput-based, Newtonsoft.Json-serialised) and are identified by
/// a combination of <see cref="ControllerProfile.ProfileName"/> and
/// <see cref="ControllerProfile.Author"/>.  Profiles can be synced to the
/// user's private cloud repo and shared to the public Games.Database.
/// </summary>
public static class ControllerProfileService
{
    private static readonly JsonSerializerOptions _json = new()
    {
        WriteIndented             = true,
        PropertyNameCaseInsensitive = true,
    };

    // ── Standard button names (mirrors SharpDX.XInput GamepadButtonFlags) ──
    public static readonly IReadOnlyList<string> ButtonNames = new[]
    {
        "A", "B", "X", "Y",
        "DPadUp", "DPadDown", "DPadLeft", "DPadRight",
        "LeftShoulder", "RightShoulder",
        "LeftTrigger",  "RightTrigger",
        "LeftThumb",    "RightThumb",
        "Start",        "Back",
    };

    // ── Path helpers ───────────────────────────────────────────────────────

    /// <summary>Returns the full path to the controller-profiles.json for a game.</summary>
    public static string GetProfilesPath(string platform, string title)
    {
        string sanitized = SanitizeFolderName(title);
        return Path.Combine(
            AppDomain.CurrentDomain.BaseDirectory,
            "Data", "GameCache", platform, sanitized,
            "controller-profiles.json");
    }

    // ── CRUD ───────────────────────────────────────────────────────────────

    /// <summary>Loads all saved profiles for a game.  Returns an empty list when none exist.</summary>
    public static List<ControllerProfile> LoadProfiles(string platform, string title)
    {
        string path = GetProfilesPath(platform, title);
        if (!File.Exists(path)) return new List<ControllerProfile>();
        try
        {
            var json = File.ReadAllText(path);
            return JsonSerializer.Deserialize<List<ControllerProfile>>(json, _json)
                   ?? new List<ControllerProfile>();
        }
        catch { return new List<ControllerProfile>(); }
    }

    /// <summary>
    /// Overwrites the profiles file for a game.  Creates parent directories as needed.
    /// </summary>
    public static void SaveProfiles(string platform, string title,
                                    IEnumerable<ControllerProfile> profiles)
    {
        string path = GetProfilesPath(platform, title);
        try
        {
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, JsonSerializer.Serialize(profiles.ToList(), _json));
        }
        catch { /* best-effort */ }
    }

    /// <summary>
    /// Upserts a profile — replaces any existing entry with the same
    /// <see cref="ControllerProfile.ProfileName"/> and <see cref="ControllerProfile.Author"/>.
    /// </summary>
    public static void AddOrUpdateProfile(string platform, string title,
                                          ControllerProfile profile)
    {
        var profiles = LoadProfiles(platform, title);
        profiles.RemoveAll(p =>
            string.Equals(p.ProfileName, profile.ProfileName, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(p.Author,      profile.Author,      StringComparison.OrdinalIgnoreCase));
        profiles.Add(profile);
        SaveProfiles(platform, title, profiles);
    }

    /// <summary>
    /// Removes the profile with the given name / author pair from the local cache.
    /// </summary>
    public static void DeleteProfile(string platform, string title,
                                     string profileName, string author)
    {
        var profiles = LoadProfiles(platform, title);
        profiles.RemoveAll(p =>
            string.Equals(p.ProfileName, profileName, StringComparison.OrdinalIgnoreCase) &&
            string.Equals(p.Author,      author,      StringComparison.OrdinalIgnoreCase));
        SaveProfiles(platform, title, profiles);
    }

    // ── Factory helpers ────────────────────────────────────────────────────

    /// <summary>
    /// Creates the "Default" profile: all buttons empty (the game handles the
    /// controller natively via XInput without any key-injection remapping).
    /// Mirrors the Default.json template generated by the Game.OS.Input PS1 script.
    /// </summary>
    public static ControllerProfile CreateDefaultProfile(string author = "") => new()
    {
        ProfileName = "Default",
        Description = "Passthrough — all buttons empty. Use when the game handles the controller natively.",
        Author      = author,
        Mappings    = BuildEmptyMappings(),
    };

    /// <summary>
    /// Creates the "Navigation" profile: D-pad → arrow keys, A → Enter, B → Escape,
    /// LB → PageUp, RB → PageDown.  Useful for menu-driven emulated games.
    /// Mirrors the Main.json template generated by the Game.OS.Input PS1 script.
    /// </summary>
    public static ControllerProfile CreateNavigationProfile(string author = "") => new()
    {
        ProfileName = "Navigation",
        Description = "D-pad = arrow keys, A = Enter, B = Escape, LB/RB = page up/down.",
        Author      = author,
        Mappings    = new Dictionary<string, ControllerButtonAction>
        {
            ["A"]             = new() { Press = "Key:Enter",    Hold = "Empty"      },
            ["B"]             = new() { Press = "Key:Escape",   Hold = "Empty"      },
            ["X"]             = new() { Press = "Empty",        Hold = "Empty"      },
            ["Y"]             = new() { Press = "Empty",        Hold = "Empty"      },
            ["DPadUp"]        = new() { Press = "Key:Up",       Hold = "Key:Up"     },
            ["DPadDown"]      = new() { Press = "Key:Down",     Hold = "Key:Down"   },
            ["DPadLeft"]      = new() { Press = "Key:Left",     Hold = "Key:Left"   },
            ["DPadRight"]     = new() { Press = "Key:Right",    Hold = "Key:Right"  },
            ["LeftShoulder"]  = new() { Press = "Key:PageUp",   Hold = "Empty"      },
            ["RightShoulder"] = new() { Press = "Key:PageDown", Hold = "Empty"      },
            ["LeftTrigger"]   = new() { Press = "Empty",        Hold = "Empty"      },
            ["RightTrigger"]  = new() { Press = "Empty",        Hold = "Empty"      },
            ["LeftThumb"]     = new() { Press = "Empty",        Hold = "Empty"      },
            ["RightThumb"]    = new() { Press = "Empty",        Hold = "Empty"      },
            ["Start"]         = new() { Press = "Empty",        Hold = "Empty"      },
            ["Back"]          = new() { Press = "Key:Escape",   Hold = "Empty"      },
        },
    };

    /// <summary>
    /// Returns a mapping dictionary where every standard button is set to "Empty".
    /// </summary>
    public static Dictionary<string, ControllerButtonAction> BuildEmptyMappings()
    {
        var dict = new Dictionary<string, ControllerButtonAction>();
        foreach (var name in ButtonNames)
            dict[name] = new ControllerButtonAction();
        return dict;
    }

    private static string SanitizeFolderName(string name)
    {
        foreach (char c in Path.GetInvalidFileNameChars())
            name = name.Replace(c, '_');
        return name;
    }
}
